orbs:
  #codecov: circleci/codecov-clojure@0.0.4
  my-orb:
    executors:
      default:
        docker:
        - image: circleci/openjdk
    commands:
      dospecialthings:
        steps:
        - run: echo "We will now do special things"
    jobs:
      myjob:
        executor: default
        steps:
        - dospecialthings
        #- codecov/upload:
        #    path: ~/tmp/results.xml

version: 2.1
workflows:
  main:
    jobs:
    - my-orb/myjob
