orbs:
  nexus-orb: orbtest/circleci-nexus-orb@dev:INT-2218


version: 2.1

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/circleci-demo-java-spring # directory where steps will run

    docker: # run the steps with Docker
    - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

    - checkout # check out source code to working directory

    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

    - run: mvn package # run the actual tests

    - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
        path: target/surefire-reports

    - store_artifacts: # store the uberjar as an artifact
        path: target/test1-1.0-SNAPSHOT.jar
        
    #### test publishing directly from the filesystem
    - nexus-orb/publish:
        filename: "target/test1-1.0-SNAPSHOT.jar"
        attributes: "-CgroupId=com.example -CartifactId=myapp -Cversion=1.${CIRCLE_BUILD_NUM} -Aextension=jar"

    ### test publishing via a mounted workspace, that's required for workflows to pass files to other build nodes
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
    - persist_to_workspace:
        # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
        # taken to be the root directory of the workspace.
        root: target
        # Must be relative path from root
        paths:
          - test1-1.0-SNAPSHOT.jar

    - nexus-orb/publish:
        workspace: "target"
        filename: "test1-1.0-SNAPSHOT.jar"
        attributes: "-CgroupId=com.example -CartifactId=myapp -Cversion=2.${CIRCLE_BUILD_NUM} -Aextension=jar"
        
    ### test running the (groovy) install script. It has not required here because our docker image already has groovy
    - nexus-orb/install # install Sonatype Nexus Repository Manager client. Only required when groovy not already available.
    
  deploy:
    executor: nexus-platform-cli
    steps:
    - nexus-orb/publish:
        # username: 
        # password: 
        # serverurl: 
        filename:  << parameters.filename >>
        # format:
        attributes: "-CgroupId=com.example -CartifactId=myapp -Cversion=3.${CIRCLE_BUILD_NUM} -Aextension=jar"
        # repository: << parameters.repository >>
        workspace: "target"
        # sonatypedir:

workflows:
 main:
   jobs:
     - build
     - deploy:
         requires:
           - build
         # context can be specified here
         # context: circlecitest  
